version: '3.8'
services:
  app:
    build: .
    command: python -m flask run --host=0.0.0.0
    volumes:
      - .:/app
  weaviate:
    image: semitechnologies/weaviate:latest
    ports:
      - "8080:8080"
